### ISSUE TITLE
Error to install package by npm

### ISSUE THREAD

**Issue by jmlavoier** [DeepElement/node-som#3]
Hi i have any problem to install by npm
Follow my npm-debug.log

``` 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-som',
1 verbose cli   '--save' ]
2 info using npm@3.8.5
3 info using node@v5.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData node-som
8 silly fetchNamedPackageData node-som
9 silly mapToRegistry name node-som
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'node-som',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'node-som',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/node-som
14 verbose request uri https://registry.npmjs.org/node-som
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:45:47 PM
17 verbose request id caf54044acf716ea
18 verbose etag "BWKT87HFE01T5HJSH5Z2L9FKK"
19 http request GET https://registry.npmjs.org/node-som
20 http 304 https://registry.npmjs.org/node-som
21 verbose headers { date: 'Sun, 26 Jun 2016 17:45:47 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"BWKT87HFE01T5HJSH5Z2L9FKK"',
21 verbose headers   age: '0',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-jfk1046-JFK',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1466963147.989257,VS0,VE112',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Sun, 26 Jun 2016 17:45:47 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"BWKT87HFE01T5HJSH5Z2L9FKK"',
22 silly get     age: '0',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-jfk1046-JFK',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1466963147.989257,VS0,VE112',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/node-som from cache
24 verbose get saving node-som to /Users/joao/.npm/registry.npmjs.org/node-som/.cache.json
25 verbose correctMkdir /Users/joao/.npm correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install node-som as a dependency of itself
43 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/joao/Sites/node-som
45 error Darwin 15.5.0
46 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-som" "--save"
47 error node v5.7.0
48 error npm  v3.8.5
49 error code ENOSELF
50 error Refusing to install node-som as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]
```

**Comment by jmlavoier** [comment]
Sorry, i discovery the  problem, my project was with the same name `node-som`.
